/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.EducationReception;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.RegistrationOrganization;
import Business.Person.Person;
import Business.User.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Chinmay
 */
public class dummyRegisterEducationPanel extends javax.swing.JPanel {

    /**
     * Creates new form dummyRegisterEducationPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organisation;
    private Enterprise etrp;
    private EcoSystem business;
   

    public dummyRegisterEducationPanel(JPanel userProcessContainer, UserAccount account, RegistrationOrganization organisation, Enterprise etrp, EcoSystem business) {
        initComponents();     
         this.userProcessContainer=userProcessContainer;
        
         this.account=account;
         this.organisation=organisation;
         this.etrp=etrp;
         this.business=business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegisterPatient = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtPersonName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailTxtfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TxtSSN = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rblFemaleGender = new javax.swing.JRadioButton();
        rblMaleGender = new javax.swing.JRadioButton();
        btnRegister = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        lblRegisterPatient.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRegisterPatient.setText("INSTITUTE REGISTRATION");

        jLabel1.setText("Name:");

        txtPersonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Age:");

        jLabel4.setText("Email");

        jLabel5.setText("SSN");

        jLabel3.setText("Gender:");

        rblFemaleGender.setText("Female");
        rblFemaleGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblFemaleGenderActionPerformed(evt);
            }
        });

        rblMaleGender.setText("Male");
        rblMaleGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblMaleGenderActionPerformed(evt);
            }
        });

        btnRegister.setText("Register Person");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRegisterPatient)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(rblMaleGender, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rblFemaleGender))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtPersonName, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                                    .addComponent(emailTxtfield)
                                    .addComponent(TxtSSN))))
                        .addGap(79, 79, 79))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegister)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblRegisterPatient)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(emailTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(TxtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rblFemaleGender)
                    .addComponent(rblMaleGender)
                    .addComponent(jLabel3))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegister)
                    .addComponent(btnBack))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPersonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonNameActionPerformed

    private void rblFemaleGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblFemaleGenderActionPerformed
        // TODO add your handling code here:
        rblMaleGender.setSelected(false);
    }//GEN-LAST:event_rblFemaleGenderActionPerformed

    private void rblMaleGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblMaleGenderActionPerformed

        // TODO add your handling code here:
        rblFemaleGender.setSelected(false);
    }//GEN-LAST:event_rblMaleGenderActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String name=txtPersonName.getText();
        String ssn  = TxtSSN.getText();
        String age=txtAge.getText();
        String email  = emailTxtfield.getText();
        if(!name.matches("[A-Za-z]+"))
        {
            JOptionPane.showMessageDialog(null, "Please enter a valid name","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!age.matches("[0-9]{2}"))
        {
            JOptionPane.showMessageDialog(null, "Please enter a valid age","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!rblMaleGender.isSelected() && !rblFemaleGender.isSelected())
        {
            JOptionPane.showMessageDialog(null, "Please select your gender","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(!ssn.matches("[0-9]{6}"))
        {
            JOptionPane.showMessageDialog(null, "Please enter a valid SSN number","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        int x = Integer.parseInt(ssn);
        boolean ch  = organisation.getPersonDirectory().isSSNnumberUnique(x);
        if(ch==false)
        {
            JOptionPane.showMessageDialog(null, "SSN number is already registered","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(!email.matches("^([a-zA-Z0-9_\\-\\.]+)@([a-zA-Z0-9_\\-\\.]+)\\.([a-zA-Z]{2,5})$"))
        {
            JOptionPane.showMessageDialog(null, "Please enter a valid Email ID","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }

        Person p=organisation.getPersonDirectory().addPerson();
        p.setPersonName(name);
        p.setAge(Integer.parseInt(age));
        if(rblMaleGender.isSelected())
        p.setGender(Person.Gender.Male);
        else
        p.setGender(Person.Gender.Female);
        p.setSsnNumber(x);
        JOptionPane.showMessageDialog(null,"suspect registered successfully");
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout)userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtSSN;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JTextField emailTxtfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblRegisterPatient;
    private javax.swing.JRadioButton rblFemaleGender;
    private javax.swing.JRadioButton rblMaleGender;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtPersonName;
    // End of variables declaration//GEN-END:variables
}
