/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.EducationReception;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.InstituteRehabOrganization;
import Business.Organization.Organization;
import static Business.Organization.Organization.OrgType.InstituteRehabOrganization;
import Business.Organization.RegistrationOrganization;
import Business.Person.Person;
import Business.User.UserAccount;
import Business.WorkRequest.WorkResponse;
import Business.SexualAssault.SexualAssualtEval;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Chinmay
 */
public class QuestionnairePanel extends javax.swing.JPanel {

    /**
     * Creates new form QuestionnairePanel
     */
       private JPanel userProcessContainer;
    private UserAccount account;
    private RegistrationOrganization organisation;
    private Enterprise etrp;
    private EcoSystem business;
    private WorkResponse wr;

  

    QuestionnairePanel(JPanel userProcessContainer, UserAccount account, Enterprise etrp, RegistrationOrganization organisation, EcoSystem business, WorkResponse wr) {
        
        initComponents();
          this.userProcessContainer = userProcessContainer;
        this.account = account;
        
        this.organisation = organisation;
        this.etrp = etrp;
        this.business = business;
        this.wr = wr;
        
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        q1YesBtn = new javax.swing.JRadioButton();
        q1NoBtn = new javax.swing.JRadioButton();
        q3YesBtn = new javax.swing.JRadioButton();
        q3NoBtn = new javax.swing.JRadioButton();
        q2YesBtn = new javax.swing.JRadioButton();
        q4YesBtn = new javax.swing.JRadioButton();
        q5YesBtn = new javax.swing.JRadioButton();
        q6YesBtn = new javax.swing.JRadioButton();
        q2NoBtn = new javax.swing.JRadioButton();
        q5NoBtn = new javax.swing.JRadioButton();
        q4NoBtn = new javax.swing.JRadioButton();
        q6NoBtn = new javax.swing.JRadioButton();
        calculateBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Questionnaire Panel");

        jLabel2.setText("Do you turn violent if u want something desperately? ");

        jLabel3.setText("Do you often feel restless or lack of focus infornt of opposite sex?");

        jLabel4.setText("Do you think you have sufficient control on your urges?");

        jLabel5.setText("Do you feel that your urges often overcomes your mind control and peace of mind?");

        jLabel6.setText("Do you feel incontrollable attraction because of clothes , looks and persona of opposite sex person?");

        jLabel7.setText("Do you feel your urges are compulsive?");

        buttonGroup1.add(q1YesBtn);
        q1YesBtn.setText("YES");
        q1YesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1YesBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(q1NoBtn);
        q1NoBtn.setText("NO");
        q1NoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1NoBtnActionPerformed(evt);
            }
        });

        buttonGroup3.add(q3YesBtn);
        q3YesBtn.setText("YES");
        q3YesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3YesBtnActionPerformed(evt);
            }
        });

        buttonGroup3.add(q3NoBtn);
        q3NoBtn.setText("NO");
        q3NoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3NoBtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(q2YesBtn);
        q2YesBtn.setText("YES");
        q2YesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2YesBtnActionPerformed(evt);
            }
        });

        buttonGroup4.add(q4YesBtn);
        q4YesBtn.setText("YES");
        q4YesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4YesBtnActionPerformed(evt);
            }
        });

        buttonGroup5.add(q5YesBtn);
        q5YesBtn.setText("YES");
        q5YesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5YesBtnActionPerformed(evt);
            }
        });

        buttonGroup6.add(q6YesBtn);
        q6YesBtn.setText("YES");
        q6YesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6YesBtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(q2NoBtn);
        q2NoBtn.setText("NO");
        q2NoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2NoBtnActionPerformed(evt);
            }
        });

        buttonGroup5.add(q5NoBtn);
        q5NoBtn.setText("NO");
        q5NoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5NoBtnActionPerformed(evt);
            }
        });

        buttonGroup4.add(q4NoBtn);
        q4NoBtn.setText("NO");
        q4NoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4NoBtnActionPerformed(evt);
            }
        });

        buttonGroup6.add(q6NoBtn);
        q6NoBtn.setText("NO");
        q6NoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q6NoBtnActionPerformed(evt);
            }
        });

        calculateBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        calculateBtn.setText("Calculate Nature Analysis and Process");
        calculateBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(q2YesBtn)
                                    .addComponent(q1YesBtn))
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(q1NoBtn)
                                    .addComponent(q2NoBtn)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(q4YesBtn)
                                    .addGap(98, 98, 98))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(q3YesBtn)
                                            .addComponent(q5YesBtn, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addComponent(q6YesBtn))
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(q6NoBtn)
                                        .addComponent(q4NoBtn)
                                        .addComponent(q3NoBtn)
                                        .addComponent(q5NoBtn))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(439, 439, 439)
                        .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(546, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel6)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q1YesBtn)
                            .addComponent(q1NoBtn))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q2YesBtn)
                            .addComponent(q2NoBtn))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q3YesBtn)
                            .addComponent(q3NoBtn))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q4YesBtn)
                            .addComponent(q4NoBtn))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q5YesBtn)
                            .addComponent(q5NoBtn))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q6YesBtn)
                            .addComponent(q6NoBtn))))
                .addGap(78, 78, 78)
                .addComponent(calculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void q1YesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1YesBtnActionPerformed
        // TODO add your handling code here:
        
        
        
        q1YesBtn.setSelected(false);
    }//GEN-LAST:event_q1YesBtnActionPerformed

    private void q1NoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1NoBtnActionPerformed
        // TODO add your handling code here:
        q1NoBtn.setSelected(false);
    }//GEN-LAST:event_q1NoBtnActionPerformed

    private void q2YesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2YesBtnActionPerformed
        // TODO add your handling code here:
        q2YesBtn.setSelected(false);
    }//GEN-LAST:event_q2YesBtnActionPerformed

    private void q2NoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2NoBtnActionPerformed
        // TODO add your handling code here:
        q2NoBtn.setSelected(false);
    }//GEN-LAST:event_q2NoBtnActionPerformed

    private void q3YesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3YesBtnActionPerformed
        // TODO add your handling code here:
        q3YesBtn.setSelected(false);
    }//GEN-LAST:event_q3YesBtnActionPerformed

    private void q3NoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3NoBtnActionPerformed
        // TODO add your handling code here:
        q3NoBtn.setSelected(false);
    }//GEN-LAST:event_q3NoBtnActionPerformed

    private void q4YesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4YesBtnActionPerformed
        // TODO add your handling code here:
        q4YesBtn.setSelected(false);
    }//GEN-LAST:event_q4YesBtnActionPerformed

    private void q4NoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4NoBtnActionPerformed
        // TODO add your handling code here:
        q4NoBtn.setSelected(false);
    }//GEN-LAST:event_q4NoBtnActionPerformed

    private void q5YesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5YesBtnActionPerformed
        // TODO add your handling code here:
        q5YesBtn.setSelected(false);
    }//GEN-LAST:event_q5YesBtnActionPerformed

    private void q5NoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5NoBtnActionPerformed
        // TODO add your handling code here:
        q5NoBtn.setSelected(false);
    }//GEN-LAST:event_q5NoBtnActionPerformed

    private void q6YesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6YesBtnActionPerformed
        // TODO add your handling code here:
        q6YesBtn.setSelected(false);
    }//GEN-LAST:event_q6YesBtnActionPerformed

    private void q6NoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q6NoBtnActionPerformed
        // TODO add your handling code here:
        q6NoBtn.setSelected(false);
    }//GEN-LAST:event_q6NoBtnActionPerformed

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
        if(!q1NoBtn.isSelected() && !q1YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question one","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(!q2NoBtn.isSelected() && !q2YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question two","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!q3NoBtn.isSelected() && !q3YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question three","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!q4NoBtn.isSelected() && !q4YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question four","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!q5NoBtn.isSelected() && !q5YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question five","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!q6NoBtn.isSelected() && !q6YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question six","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
       int count  = 0;
       
       if(q1YesBtn.isSelected()==true)
       {
       count++;
       }
       
        if(q2YesBtn.isSelected()==true)
       {
       count++;
       }
         if(q3YesBtn.isSelected()==true)
       {
       count++;
       }
          if(q4YesBtn.isSelected()==true)
       {
       count++;
       }
          
          if(q5YesBtn.isSelected()==true)
       {
       count++;
       }
             if(q6YesBtn.isSelected()==true)
       {
       count++;
       }
       
       Random r = new Random();
       int x  = r.nextInt(4)+1;
       
       int natAnalysis = x*count;
       
        SexualAssualtEval sobj= (SexualAssualtEval)wr.getResult()[0];
        if(sobj!=null) 
        {sobj.setNatureAnalysis(natAnalysis);
         }
//        
//       int sum =  sobj.getTotal();
//       int cran = sobj.getCrimeAnalysisIndex();
//       int nat = sobj.getNatureAnalysis();
//       System.out.println(cran);
//       System.out.println(nat);
         if(wr!=null)
         {
             InstituteRehabOrganization rehaborg  = null;
             boolean flag=false;
             for(Person p:organisation.getPersonDirectory().getLstPerson())
             {
            //     if(p.getPersonName().equals(wr.getPerson().getPersonName())&&p.getSsnNumber().equals(wr.getPerson().getSsnNumber()))
              
                 if(p.getSsnNumber()==(wr.getPerson().getSsnNumber()))
                 {
                   flag=true;
                   break;
                 }
             }
             if(flag)
             {
              for(Organization org  : etrp.getOrdDir().getLstOrganisation())
             {
                if(org instanceof InstituteRehabOrganization)
                {
                                 rehaborg  = (InstituteRehabOrganization) org;
                                 break;
                }
             }   
             }
             if(rehaborg!=null)
             {
             rehaborg.getWorkQueue().getLstWorkRequest().add(wr);
           //  wr.setOl(WorkRequest.OperationalLevel.SP);
             wr.setReceiver(null);
             wr.setStatus("Pending - Sent to rehab organization");
           JOptionPane.showMessageDialog(null, "Request sent to rehab organization");
             }
             
             
         }     
//             
//         }
//        // TODO add your handling code here:
//    }                                          
    else
        {
            JOptionPane.showMessageDialog(null,"Please select a request from table","WARNING",JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_calculateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton q1NoBtn;
    private javax.swing.JRadioButton q1YesBtn;
    private javax.swing.JRadioButton q2NoBtn;
    private javax.swing.JRadioButton q2YesBtn;
    private javax.swing.JRadioButton q3NoBtn;
    private javax.swing.JRadioButton q3YesBtn;
    private javax.swing.JRadioButton q4NoBtn;
    private javax.swing.JRadioButton q4YesBtn;
    private javax.swing.JRadioButton q5NoBtn;
    private javax.swing.JRadioButton q5YesBtn;
    private javax.swing.JRadioButton q6NoBtn;
    private javax.swing.JRadioButton q6YesBtn;
    // End of variables declaration//GEN-END:variables
}