/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.InstituteRehab;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.User.UserAccount;
import Business.WorkRequest.WorkResponse;
import Business.SexualAssault.SexualAssualtEval;
import java.awt.CardLayout;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Chinmay
 */
public class QuestionnaireForThreatPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuestionnaireForThreatPanel
     */
    
      private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organisation;
    private Enterprise etrp;
    private EcoSystem business;
    private WorkResponse wr;
    public QuestionnaireForThreatPanel() {
        initComponents();
    }

    QuestionnaireForThreatPanel(JPanel userProcessContainer, UserAccount account, Enterprise etrp, Organization organisation, EcoSystem business, WorkResponse wr) {
        initComponents();
          
       this.userProcessContainer=userProcessContainer;
       this.organisation=organisation;
        this.account=account;
        this.etrp=etrp;
        this.business=business;
        this.wr  = wr;
        
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        q1YesBtn = new javax.swing.JRadioButton();
        q1NoBtn = new javax.swing.JRadioButton();
        q2YesBtn = new javax.swing.JRadioButton();
        q2NoBtn = new javax.swing.JRadioButton();
        q3YesBtn = new javax.swing.JRadioButton();
        q3NoBtn = new javax.swing.JRadioButton();
        q6YesBtn = new javax.swing.JRadioButton();
        q5YesBtn = new javax.swing.JRadioButton();
        q5NoBtn = new javax.swing.JRadioButton();
        q6NoBtn = new javax.swing.JRadioButton();
        q4YesBtn = new javax.swing.JRadioButton();
        q4NoBtn = new javax.swing.JRadioButton();
        NextBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Questionnaire");

        jLabel2.setText("Do you feel any change in your urges?");

        jLabel3.setText("Do you feel this program is cultivating values in you?");

        jLabel4.setText("Is this program helping you changing your outlook towards opposite sex?");

        jLabel5.setText("Upto what level you this program has brought change in you?");

        jLabel6.setText("Have you often get enticed by your fellow opposite sex students?");

        jLabel7.setText("You feel your urges are compulsive?");

        buttonGroup1.add(q1YesBtn);
        q1YesBtn.setText("YES");
        q1YesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1YesBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(q1NoBtn);
        q1NoBtn.setText("NO");
        q1NoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1NoBtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(q2YesBtn);
        q2YesBtn.setText("YES");

        buttonGroup2.add(q2NoBtn);
        q2NoBtn.setText("NO");

        buttonGroup3.add(q3YesBtn);
        q3YesBtn.setText("YES");

        buttonGroup3.add(q3NoBtn);
        q3NoBtn.setText("NO");

        buttonGroup6.add(q6YesBtn);
        q6YesBtn.setText("YES");

        buttonGroup5.add(q5YesBtn);
        q5YesBtn.setText("YES");

        buttonGroup5.add(q5NoBtn);
        q5NoBtn.setText("NO");

        buttonGroup6.add(q6NoBtn);
        q6NoBtn.setText("NO");

        buttonGroup4.add(q4YesBtn);
        q4YesBtn.setText("YES");

        buttonGroup4.add(q4NoBtn);
        q4NoBtn.setText("NO");

        NextBtn.setBackground(new java.awt.Color(255, 51, 51));
        NextBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        NextBtn.setText("Next");
        NextBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        NextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(NextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(338, 338, 338)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(q5YesBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(q5NoBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(q4YesBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(q4NoBtn))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(q6YesBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(q6NoBtn)))))
                        .addContainerGap(163, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))
                                .addGap(275, 275, 275)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(q2YesBtn)
                                            .addGap(18, 18, 18)
                                            .addComponent(q2NoBtn))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(q1YesBtn)
                                            .addGap(18, 18, 18)
                                            .addComponent(q1NoBtn)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(q3YesBtn)
                                        .addGap(18, 18, 18)
                                        .addComponent(q3NoBtn))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(414, 414, 414)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel3)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(q1YesBtn)
                                    .addComponent(q1NoBtn))
                                .addGap(62, 62, 62))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(q2YesBtn)
                                .addComponent(q2NoBtn)))
                        .addGap(63, 63, 63))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(q3YesBtn)
                        .addComponent(q3NoBtn)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(q4YesBtn)
                                .addComponent(q4NoBtn)))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(q5YesBtn)
                        .addComponent(q5NoBtn)))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(q6YesBtn)
                    .addComponent(q6NoBtn))
                .addGap(83, 83, 83)
                .addComponent(NextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void q1NoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1NoBtnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_q1NoBtnActionPerformed

    private void q1YesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1YesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1YesBtnActionPerformed

    private void NextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextBtnActionPerformed

//        if(wr.isIsComplete())
//        {
//            JOptionPane.showMessageDialog(null,"Request is already completed");
//           return; 
//        }
//        if(!wr.getOl().equals(WorkResponse.OperationalLevel.InstituteRehab))
//        {
//            JOptionPane.showMessageDialog(null,"Request is being serviced at other operational level");
//            return;
//        }
//        if(wr.getReceiver()!=account)
//        {
//           return; 
//        }
        if(!q1NoBtn.isSelected() && !q1YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question one","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(!q2NoBtn.isSelected() && !q2YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question two","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!q3NoBtn.isSelected() && !q3YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question three","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!q4NoBtn.isSelected() && !q4YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question four","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!q5NoBtn.isSelected() && !q5YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question five","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!q6NoBtn.isSelected() && !q6YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question six","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }

        int count  = 0;
       
       if(q1NoBtn.isSelected() )
       {
       count++;
       }
       
        if(q2NoBtn.isSelected()==true)
       {
       count++;
       }
         if(q3NoBtn.isSelected()==true)
       {
       count++;
       }
          if(q5NoBtn.isSelected()==true)
       {
       count++;
       }
          
             if(q6YesBtn.isSelected()==true)
       {
       count++;
       }
             
           if(q4NoBtn.isSelected()==true)
       {
       count++;
       }
           Random r  = new Random();
           int x  = r.nextInt(6)+1;
           
           int socialThreat = count*x ;
           
             SexualAssualtEval sobj= (SexualAssualtEval)wr.getResult()[0];
        if(sobj!=null) 
        {sobj.setSocialThreatIndex(socialThreat);
         }
       //  WorkResponse wr=(WorkResponse) tblWorkRequest.getValueAt(selectedRow,0);
          TestResultFailPanel testresultfailpanel = new TestResultFailPanel(userProcessContainer,account,etrp, organisation,business,wr);
        userProcessContainer.add("TestResultFailPanel", testresultfailpanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_NextBtnActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NextBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton q1NoBtn;
    private javax.swing.JRadioButton q1YesBtn;
    private javax.swing.JRadioButton q2NoBtn;
    private javax.swing.JRadioButton q2YesBtn;
    private javax.swing.JRadioButton q3NoBtn;
    private javax.swing.JRadioButton q3YesBtn;
    private javax.swing.JRadioButton q4NoBtn;
    private javax.swing.JRadioButton q4YesBtn;
    private javax.swing.JRadioButton q5NoBtn;
    private javax.swing.JRadioButton q5YesBtn;
    private javax.swing.JRadioButton q6NoBtn;
    private javax.swing.JRadioButton q6YesBtn;
    // End of variables declaration//GEN-END:variables
}
