/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.InstituteRehab;

import Business.EcoSystem;
import Business.Enterprise.EducationInstituteEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.User.UserAccount;
import Business.WorkRequest.WorkResponse;
import Business.SexualAssault.SexualAssualtEval;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Chinmay
 */
public class TestResultFailPanel extends javax.swing.JPanel {

    /**
     * Creates new form TestResultFailPanel
     */
      private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organisation;
    private Enterprise etrp;
    private EducationInstituteEnterprise eie=null;
    private EcoSystem business;
    private WorkResponse wr;

    TestResultFailPanel(JPanel userProcessContainer, UserAccount account, Enterprise etrp, Organization organisation, EcoSystem business, WorkResponse wr) {
         initComponents();
          this.userProcessContainer=userProcessContainer;
       this.organisation=organisation;
        this.account=account;
        this.etrp=etrp;
        this.business=business;
        this.eie=(EducationInstituteEnterprise) etrp;
        this.wr  = wr;
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        q6YesBtn = new javax.swing.JRadioButton();
        q5YesBtn = new javax.swing.JRadioButton();
        q4YesBtn = new javax.swing.JRadioButton();
        q3YesBtn = new javax.swing.JRadioButton();
        q2YesBtn = new javax.swing.JRadioButton();
        q1YesBtn = new javax.swing.JRadioButton();
        q1NoBtn = new javax.swing.JRadioButton();
        q2NoBtn = new javax.swing.JRadioButton();
        q3NoBtn = new javax.swing.JRadioButton();
        q4NoBtn = new javax.swing.JRadioButton();
        q5NoBtn = new javax.swing.JRadioButton();
        q6NoBtn = new javax.swing.JRadioButton();
        CalculateBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setText("Has person passed in tests regarding mind control?");

        jLabel3.setText("Has person successfully able to complete projects on sexual assaults?");

        jLabel4.setText("Has person shown violence anytime during the course of the event?");

        jLabel5.setText("Has person acquired the values which are taught in the session?");

        jLabel6.setText("Has person able to maintain his composure on various scenarios he was exposed to?");

        jLabel7.setText("Has Person shown any susceptibility to immoral sexual scenarios?");

        buttonGroup6.add(q6YesBtn);
        q6YesBtn.setText("YES");

        buttonGroup5.add(q5YesBtn);
        q5YesBtn.setText("YES");

        buttonGroup4.add(q4YesBtn);
        q4YesBtn.setText("YES");

        buttonGroup3.add(q3YesBtn);
        q3YesBtn.setText("YES");

        buttonGroup2.add(q2YesBtn);
        q2YesBtn.setText("YES");

        buttonGroup1.add(q1YesBtn);
        q1YesBtn.setText("YES");
        q1YesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1YesBtnActionPerformed(evt);
            }
        });

        buttonGroup1.add(q1NoBtn);
        q1NoBtn.setText("NO");
        q1NoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1NoBtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(q2NoBtn);
        q2NoBtn.setText("NO");

        buttonGroup3.add(q3NoBtn);
        q3NoBtn.setText("NO");

        buttonGroup4.add(q4NoBtn);
        q4NoBtn.setText("NO");

        buttonGroup5.add(q5NoBtn);
        q5NoBtn.setText("NO");

        buttonGroup6.add(q6NoBtn);
        q6NoBtn.setText("NO");

        CalculateBtn.setBackground(new java.awt.Color(255, 51, 51));
        CalculateBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        CalculateBtn.setText("Calculate");
        CalculateBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CalculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalculateBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Questionnaire");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CalculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q1YesBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q2YesBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q3YesBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q6YesBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q5YesBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q4YesBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(q1NoBtn))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(q2NoBtn)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(q3NoBtn)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(q5NoBtn)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(q6NoBtn)
                                    .addComponent(q4NoBtn))))))
                .addContainerGap(398, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q1YesBtn)
                            .addComponent(q1NoBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q2YesBtn)
                            .addComponent(q2NoBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q3YesBtn)
                            .addComponent(q3NoBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q4YesBtn)
                            .addComponent(q4NoBtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q5NoBtn)
                            .addComponent(q5YesBtn))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q6YesBtn)
                            .addComponent(q6NoBtn))))
                .addGap(73, 73, 73)
                .addComponent(CalculateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(253, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void q1YesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1YesBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q1YesBtnActionPerformed

    private void q1NoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1NoBtnActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_q1NoBtnActionPerformed

    private void CalculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalculateBtnActionPerformed

        if(wr.isIsComplete())
        {
            JOptionPane.showMessageDialog(null,"Request has already been completed");
            return;
        }
        
        if(!q1NoBtn.isSelected() && !q1YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question one","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if(!q2NoBtn.isSelected() && !q2YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question two","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!q3NoBtn.isSelected() && !q3YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question three","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!q4NoBtn.isSelected() && !q4YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question four","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!q5NoBtn.isSelected() && !q5YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question five","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        if(!q6NoBtn.isSelected() && !q6YesBtn.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question six","WARNING",JOptionPane.WARNING_MESSAGE);
            return;
        }
        int count  = 0;

        if(q1NoBtn.isSelected()==true)
        {
            count++;
        }

        if(q2NoBtn.isSelected()==true)
        {
            count++;
        }
        if(q3YesBtn.isSelected()==true)
        {
            count++;
        }
        if(q5NoBtn.isSelected()==true)
        {
            count++;
        }

        if(q6YesBtn.isSelected()==true)
        {
            count++;
        }

        if(q4NoBtn.isSelected()==true)
        {
            count++;
        }

        
        int testresult = count *4;

        SexualAssualtEval sobj= (SexualAssualtEval)wr.getResult()[0];
        if(sobj!=null)
        {sobj.setTestResults(testresult);
        }
        sobj.CalcualteTotal();
        eie.getAssualtDir().getLstevents().add(sobj);
        wr.setIsComplete(true);
        JOptionPane.showMessageDialog(null,"Request completed successfully");
        
       // System.out.println(sobj.getCrimeAnalysisIndex());
       // System.out.println(sobj.getNatureAnalysis());
       // System.out.println(sobj.getSocialThreatIndex());
       // System.out.println(sobj.getTestResults());
    }//GEN-LAST:event_CalculateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalculateBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton q1NoBtn;
    private javax.swing.JRadioButton q1YesBtn;
    private javax.swing.JRadioButton q2NoBtn;
    private javax.swing.JRadioButton q2YesBtn;
    private javax.swing.JRadioButton q3NoBtn;
    private javax.swing.JRadioButton q3YesBtn;
    private javax.swing.JRadioButton q4NoBtn;
    private javax.swing.JRadioButton q4YesBtn;
    private javax.swing.JRadioButton q5NoBtn;
    private javax.swing.JRadioButton q5YesBtn;
    private javax.swing.JRadioButton q6NoBtn;
    private javax.swing.JRadioButton q6YesBtn;
    // End of variables declaration//GEN-END:variables
}
