/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.PoliceWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.User.UserAccount;
import Interface.LabWorkArea.MonitorPatientVitalSignJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chinmay
 */
public class ViewCriminalPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCriminalForm
     */
   
      private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organisation;
    private Enterprise etrp;
    private EcoSystem business;

    ViewCriminalPanel(JPanel userProcessContainer, UserAccount account, Organization organisation, Enterprise etrp, EcoSystem business) {
       initComponents();
       this.userProcessContainer = userProcessContainer;
        this.account = account;
        
        this.organisation = organisation;
        this.etrp = etrp;
        this.business = business;
        populateSuspect();
        
       // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void populateSuspect()
    {
         DefaultTableModel dtm=(DefaultTableModel) SuspectTbl.getModel();
       for(Person p:organisation.getPersonDirectory().getLstPerson())
       {
         Object[] row=new Object[4];
         row[0]=p;
         row[1]=p.getAge();
         row[2]=p.getGender().getValue();
         row[3]=p.getSsnNumber();
         dtm.addRow(row);
       }
  
    
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InterrogateBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SuspectTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        InterrogateBtn.setBackground(new java.awt.Color(255, 51, 51));
        InterrogateBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        InterrogateBtn.setText("Interrogate");
        InterrogateBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        InterrogateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InterrogateBtnActionPerformed(evt);
            }
        });

        backBtn.setBackground(new java.awt.Color(255, 51, 51));
        backBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        removeBtn.setBackground(new java.awt.Color(255, 51, 51));
        removeBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        removeBtn.setText("Remove");
        removeBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });

        SuspectTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Gender", "SSN"
            }
        ));
        jScrollPane1.setViewportView(SuspectTbl);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("VIEW CRIMINAL PANEL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(InterrogateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(258, 258, 258)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(290, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(InterrogateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(289, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        userProcessContainer.remove(this);
        ((CardLayout)userProcessContainer.getLayout()).previous(userProcessContainer);
        // TODO add your handling code here:
    }//GEN-LAST:event_backBtnActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
      int selectedRow=  SuspectTbl
              .getSelectedRow();
        if(selectedRow>-1)
        {
            Person p=(Person) SuspectTbl.getValueAt(selectedRow,0);
            int op=JOptionPane.showConfirmDialog(null,"Are you sure you want to remove this Suspect?");
            if(op==0)
            {
            organisation.getPersonDirectory().removePerson(p);
            JOptionPane.showMessageDialog(null,"Suspect Removed successfully");
            }
            else
                return;
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a suspect from table","WARNING",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_removeBtnActionPerformed

    private void InterrogateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InterrogateBtnActionPerformed
         int selectedRow=SuspectTbl.getSelectedRow();
        if(selectedRow>-1)
        {
            Person p=(Person) SuspectTbl.getValueAt(selectedRow,0);
            if(p!=null)
            {
                

           // userProcessContainer.add("MonitorCriminalPanel",new InterrogatePanel(userProcessContainer,p,account,organisation,etrp,business));
          //  ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);

            userProcessContainer.add("MonitorCriminalPanel",new DummyInterrogatePanel(userProcessContainer,p,account,organisation,etrp,business));
            ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);

            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a patient from table","WARNING",JOptionPane.WARNING_MESSAGE);
        }
                                                    
    }//GEN-LAST:event_InterrogateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InterrogateBtn;
    private javax.swing.JTable SuspectTbl;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeBtn;
    // End of variables declaration//GEN-END:variables
}
