/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdminWorkArea;

import Business.DrugAbuseControl.DrugEvaluation;
import Business.EcoSystem;
import Business.Enterprise.DrugFreeEnterprise;
import Business.Enterprise.Enterprise;
import Business.Organization.AddictionRecoveryOrganization;
import Business.Organization.CounsellorOrganization;
import Business.Organization.Organization;
import Business.User.UserAccount;
import Business.WorkRequest.WorkResponse;
import javax.swing.JPanel;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Suyog Sathe
 */
public class EnterpriseQuestionnaireJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private WorkResponse wr;
    private UserAccount ua;
    private Enterprise enterprise;
    private EcoSystem system;

    EnterpriseQuestionnaireJPanel(JPanel userProcessContainer, WorkResponse wr, UserAccount ua, Enterprise enterprise, EcoSystem system) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.wr=wr;
       this.ua=ua;
       this.enterprise=enterprise;
       this.system=system;
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        backBtn = new javax.swing.JButton();
        submitBtn = new javax.swing.JButton();
        q2yes = new javax.swing.JRadioButton();
        q1no = new javax.swing.JRadioButton();
        q1yes = new javax.swing.JRadioButton();
        q2no = new javax.swing.JRadioButton();
        q3yes = new javax.swing.JRadioButton();
        q3no = new javax.swing.JRadioButton();
        q4yes = new javax.swing.JRadioButton();
        q4no = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("General Questionnaire");

        jLabel2.setText("Do you have any problem living with your family?");

        jLabel3.setText("Do you have friends which do the same thing?");

        jLabel4.setText("Have you ever visited a counsellor/advisor before?");

        jLabel5.setText("Are you stressed or depressed??");

        jLabel6.setText("Tell something about yourself:");

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        backBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        backBtn.setText("back");
        backBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        submitBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        buttonGroup2.add(q2yes);
        q2yes.setText("Yes");
        q2yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2yesActionPerformed(evt);
            }
        });

        buttonGroup1.add(q1no);
        q1no.setText("No");

        buttonGroup1.add(q1yes);
        q1yes.setText("Yes");

        buttonGroup2.add(q2no);
        q2no.setText("No");

        buttonGroup3.add(q3yes);
        q3yes.setText("Yes");

        buttonGroup3.add(q3no);
        q3no.setText("No");

        buttonGroup4.add(q4yes);
        q4yes.setText("Yes");

        buttonGroup4.add(q4no);
        q4no.setText("No");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane1))
                        .addGap(330, 330, 330)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q1yes)
                            .addComponent(q2yes)
                            .addComponent(q3yes)
                            .addComponent(q4yes))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q2no)
                            .addComponent(q1no)
                            .addComponent(q3no)
                            .addComponent(q4no))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(q1yes)
                    .addComponent(q1no))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(q2yes)
                    .addComponent(q2no))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q3yes)
                            .addComponent(q3no)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q4no)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(q4yes)
                                .addComponent(jLabel5)))))
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(86, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
//       int selectedRow = drugTable.getSelectedRow();
//        if (selectedRow > -1) {
//            WorkResponse wr = (WorkResponse) drugTable.getValueAt(selectedRow, 0);
            if (wr != null) {
                if (!wr.getOl().equals(WorkRequest.OperationalLevel.DrugFree)) {
                    JOptionPane.showMessageDialog(null, "Request is being serviced at " + wr.getOl().name() + " operational level", "WARNING", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                if (wr.getReceiver() != ua) {
                    JOptionPane.showMessageDialog(null, "Request is not assigned to current user", "WARNING", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                CounsellorOrganization co = null;
                AddictionRecoveryOrganization aro = null;
                String pri=(String) wr.getResult()[1];
                
                
//                CounsellorOrganization co = null;
//                AddictionRecoveryOrganization aro = null;
//                if (wr.getResult()[0].equals("Mediums")) {
////            for(Network net :system.getNetworkDir().getLstNetwork())
//                    // {
//                    for (Organization o : enterprise.getOrdDir().getLstOrganisation()) {
//                        if (o instanceof AddictionRecoveryOrganization) {
//                            aro = (AddictionRecoveryOrganization) o;
//                            break;
//                        }
//                    }
//              if(aro!=null)
//              {
//                  break;
//              }

                //if (aro != null) {
               
                 int count = 0;
        if (!wr.isIsComplete()) {
            if (!q1yes.isSelected() && !q1no.isSelected()) {
                JOptionPane.showMessageDialog(null, "Please select atleast one option", "WARNING", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (q1yes.isSelected()) {
                count++;
            }
            if (!q2yes.isSelected() && !q2no.isSelected()) {
                JOptionPane.showMessageDialog(null, "Please select atleast one option", "WARNING", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (q2yes.isSelected()) {
                count++;
            }
            if (!q3yes.isSelected() && !q3no.isSelected()) {
                JOptionPane.showMessageDialog(null, "Please select atleast one option", "WARNING", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (q3yes.isSelected()) {
                count++;
            }
            if (!q4yes.isSelected() && !q4no.isSelected()) {
                JOptionPane.showMessageDialog(null, "Please select atleast one option", "WARNING", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (q4yes.isSelected()) {
                count++;
            }
            
            DrugEvaluation de = (DrugEvaluation) wr.getResult()[0];
            
            if(de!=null)
        {
        int sum=de.getD();
        sum=sum+count*6;
        de.setD(sum);
        }
        //wr.setReceiver(null);
        DrugFreeEnterprise dfe=null;
        if(enterprise instanceof DrugFreeEnterprise)
        {     
           dfe =(DrugFreeEnterprise) enterprise;
        }
        boolean flag=true;
        if(dfe!=null)
        {
            for(DrugEvaluation dev:dfe.getDrugRep().getLstDrugEvaluation())
            {
                if(dev.getP()==wr.getPerson())
                {
                  flag=false;  
                }
            }
            if(flag)
            dfe.getDrugRep().addDrugEvaluation(de); 
        }
            
                if(pri!=null)
                {
                if (pri.equalsIgnoreCase("Medium")) {
//            for(Network net :system.getNetworkDir().getLstNetwork())
                    // {
                    for (Organization o : enterprise.getOrdDir().getLstOrganisation()) {
                        if (o instanceof AddictionRecoveryOrganization) {
                            aro = (AddictionRecoveryOrganization) o;
                            break;
                        }
                    }
//              if(aro!=null)
//              {
//                  break;
//              }

                    if (aro != null) {
                        wr.setReceiver(null);
                        wr.setOl(WorkRequest.OperationalLevel.AddictionRecovery);
                        wr.setStatus("Pending-Request sent to Addiction Recovery Organization");
                        ua.getWorkQueue().getLstWorkRequest().add(wr);
                        aro.getWorkQueue().getLstWorkRequest().add(wr);
                        JOptionPane.showMessageDialog(null, "Request sent to Addiction Recovery Organization");
                       
                    }
                }
            else {
//                for(Network net :system.getNetworkDir().getLstNetwork())
//            {
                    for (Organization o : enterprise.getOrdDir().getLstOrganisation()) {
                        if (o instanceof CounsellorOrganization) {
                            co = (CounsellorOrganization) o;
                            break;
                        }
                    }
//                    if (co != null) {
//                        break;
//                    }
                    //    }
                    if (co != null) {
                        wr.setReceiver(null);
                        wr.setOl(WorkRequest.OperationalLevel.CounsellingOrganization); //to put enterprises and organizations in operational level
                        co.getWorkQueue().getLstWorkRequest().add(wr);
                        ua.getWorkQueue().getLstWorkRequest().add(wr);
                        wr.setStatus("Pending-Request sent to Counselling Organization");
                        JOptionPane.showMessageDialog(null, "Request sent to Counselling Organization");
                        
                    }

                }
                //

            }
            }
        
         else {
            JOptionPane.showMessageDialog(null, "Please select a row from table", "WARNING", JOptionPane.WARNING_MESSAGE);
        }
               
            }
    }//GEN-LAST:event_submitBtnActionPerformed

    private void q2yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2yesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_q2yesActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
       userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton q1no;
    private javax.swing.JRadioButton q1yes;
    private javax.swing.JRadioButton q2no;
    private javax.swing.JRadioButton q2yes;
    private javax.swing.JRadioButton q3no;
    private javax.swing.JRadioButton q3yes;
    private javax.swing.JRadioButton q4no;
    private javax.swing.JRadioButton q4yes;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
