/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdminWorkArea;

import Business.DrugAbuseControl.DrugEvaluation;
import Business.EcoSystem;
import Business.Enterprise.DrugFreeEnterprise;
import Business.Enterprise.Enterprise;
import Business.SexualAssault.SexualAssualtEval;
import Business.User.UserAccount;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Suyog Sathe
 */
public class ManageDrugAnalysisJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount ua;
    private Enterprise enterprise;
    private EcoSystem system;
    private DrugFreeEnterprise dfe = null;

    ManageDrugAnalysisJPanel(JPanel userProcessContainer, UserAccount ua, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ua = ua;
        this.enterprise = enterprise;
        this.system = system;
        dfe = (DrugFreeEnterprise) this.enterprise;
        populateCharBox();
    }

    public void populateCharBox() {
        chartBox.removeAllItems();
        chartBox.addItem("Bar Chart");
        chartBox.addItem("Pie Chart");

    }

    public void populateBarGraph() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        DrugEvaluation drugVal = null;
        for (DrugEvaluation drug : dfe.getDrugRep().getLstDrugEvaluation()) {
            drugVal = drug;
            break;
        }
        if (drugVal != null) {
            dataset.setValue(drugVal.getA(), "Marks", "Natural Factors");
            dataset.setValue(drugVal.getB(), "Marks", "Environmental Factors");
            dataset.setValue(drugVal.getC(), "Marks", "Personal Factors");
            dataset.setValue(drugVal.getD(), "Marks", "Mental Factors");
            JFreeChart chart = ChartFactory.createBarChart("Drug Abuse Evaulation", "Factors", "Values", dataset, PlotOrientation.VERTICAL, false, true, false);
            CategoryPlot p = chart.getCategoryPlot();
            p.setRangeGridlinePaint(Color.BLACK);
            ChartFrame frame = new ChartFrame("Bar Chart for student", chart);
            frame.setVisible(true);
            frame.setSize(1000, 1000);
        }
    }

    public void populatePieCharts() {
        DefaultPieDataset dt = new DefaultPieDataset();
        // dt.setValue(file,width);
        DrugEvaluation drugVal = null;
        for (DrugEvaluation drug : dfe.getDrugRep().getLstDrugEvaluation()) {
            drugVal = drug;
            break;
        }
        if (drugVal != null) {
        dt.setValue("Natural Factors", new Integer(drugVal.getA()));
        dt.setValue("Environmental Factors", new Integer(drugVal.getB()));
        dt.setValue("Personal Factors", new Integer(drugVal.getC()));
        dt.setValue("Mental Factors", new Integer(drugVal.getD()));
        JFreeChart chart = ChartFactory.createPieChart("Pie Chart", dt, true, true, true);
        PiePlot p = (PiePlot) chart.getPlot();
        // p.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame = new ChartFrame("PieChart", chart);
        frame.setVisible(true);
        frame.setSize(1000, 1000);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chartBox = new javax.swing.JComboBox<>();
        displayBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Drug Abuse Case - ANALYSIS");

        chartBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        chartBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartBoxActionPerformed(evt);
            }
        });

        displayBtn.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 16)); // NOI18N
        displayBtn.setForeground(new java.awt.Color(51, 51, 51));
        displayBtn.setText("Display ");
        displayBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 16)); // NOI18N
        jLabel2.setText("Select type of Chart:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(displayBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chartBox, 0, 155, Short.MAX_VALUE))))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chartBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        String bar = (String) chartBox.getSelectedItem();
        if (bar.equalsIgnoreCase("Bar Chart")) {
            populateBarGraph();
        } else {
            populatePieCharts();
        }

    }//GEN-LAST:event_displayBtnActionPerformed

    private void chartBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartBoxActionPerformed
        
    }//GEN-LAST:event_chartBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> chartBox;
    private javax.swing.JButton displayBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
