/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdminWorkArea;

import Business.EcoSystem;
import Business.Enterprise.EducationInstituteEnterprise;
import Business.Enterprise.Enterprise;
import Business.SexualAssault.Event;
import Business.SexualAssault.SexualAssualtEval;
import Business.User.UserAccount;
import java.awt.Color;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Chinmay
 */
public class ManageDataAnalysisEducationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDataAnalysisEducationJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount ua;
    private Enterprise enterprise;
    private EcoSystem system;
    private EducationInstituteEnterprise eie=null;

    public ManageDataAnalysisEducationJPanel(JPanel userProcessContainer, UserAccount ua, Enterprise enterprise, EcoSystem system) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.ua=ua;
       this.enterprise=enterprise;
       this.system=system;
       eie=(EducationInstituteEnterprise) this.enterprise;
       populateCharBox();
       
    }

     public void populateCharBox() {
        popCombo.removeAllItems();
        popCombo.addItem("Bar Chart");
        popCombo.addItem("Pie Chart");

    }
     
         public void populatePieCharts() {
        DefaultPieDataset dt = new DefaultPieDataset();
        // dt.setValue(file,width);
       // DrugEvaluation drugVal = null;
       SexualAssualtEval saeval=null;
        for (SexualAssualtEval e :eie.getAssualtDir().getLstevents()) {
            saeval= e;
            break;
        }
        if (saeval != null) {
        dt.setValue("CrimeAnalysis", new Integer(saeval.getCrimeAnalysisIndex()));
        dt.setValue("NatureAnalysis", new Integer(saeval.getNatureAnalysis()));
        dt.setValue("SocialThreatIndex", new Integer(saeval.getSocialThreatIndex()));
        dt.setValue("TestResults", new Integer(saeval.getTestResults()));
        JFreeChart chart = ChartFactory.createPieChart("Pie Chart", dt, true, true, true);
        PiePlot p = (PiePlot) chart.getPlot();
        // p.setForegroundAlpha(TOP_ALIGNMENT);
        ChartFrame frame = new ChartFrame("PieChart", chart);
        frame.setVisible(true);
        frame.setSize(1000, 1000);
    }
    }
         
         public void populateBarGraphs()
         {
            DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        SexualAssualtEval saeval=null;
        for(SexualAssualtEval e:eie.getAssualtDir().getLstevents())
        {
         saeval=e;
         //dataset.setValue(saeval.getCrimeAnalysisIndex(),"Marks","CrimeAnalysis");
         break;
        }
        if(saeval!=null)
        {
        dataset.setValue(saeval.getCrimeAnalysisIndex(),"Marks","CrimeAnalysis");
        dataset.setValue(saeval.getNatureAnalysis(),"Marks","NatureAnalysis");
        dataset.setValue(saeval.getSocialThreatIndex(),"Marks","SocialThreatIndex");
        dataset.setValue(saeval.getTestResults(),"Marks","TestResults");
        JFreeChart chart=ChartFactory.createBarChart("Sexual Assault evaluation","Factors", "Values", dataset,PlotOrientation.VERTICAL,false,true,false);
        CategoryPlot p=chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.BLACK);
        ChartFrame frame=new ChartFrame("Bar Chart for student",chart);
        frame.setVisible(true);
        frame.setSize(350,250);
        }
         
         
         
         }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        popCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        jButton1.setText("View details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        popCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Data Analysis");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(popCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(popCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jButton1)
                .addGap(106, 106, 106))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
  String bar = (String) popCombo.getSelectedItem();
        if (bar.equalsIgnoreCase("Bar Chart")) {
            populateBarGraphs();
        } else {
            populatePieCharts();
        }        

// TODO add your handling code here:
//        DefaultCategoryDataset dataset=new DefaultCategoryDataset();
//        SexualAssualtEval saeval=null;
//        for(SexualAssualtEval e:eie.getAssualtDir().getLstevents())
//        {
//         saeval=e;
//         //dataset.setValue(saeval.getCrimeAnalysisIndex(),"Marks","CrimeAnalysis");
//         break;
//        }
//        if(saeval!=null)
//        {
//        dataset.setValue(saeval.getCrimeAnalysisIndex(),"Marks","CrimeAnalysis");
//        dataset.setValue(saeval.getNatureAnalysis(),"Marks","NatureAnalysis");
//        dataset.setValue(saeval.getSocialThreatIndex(),"Marks","SocialThreatIndex");
//        dataset.setValue(saeval.getTestResults(),"Marks","TestResults");
//        JFreeChart chart=ChartFactory.createBarChart("Sexual Assault evaluation","Factors", "Values", dataset,PlotOrientation.VERTICAL,false,true,false);
//        CategoryPlot p=chart.getCategoryPlot();
//        p.setRangeGridlinePaint(Color.BLACK);
//        ChartFrame frame=new ChartFrame("Bar Chart for student",chart);
//        frame.setVisible(true);
//        frame.setSize(350,250);
//        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
       public void populateBarcharts()
       {
              DefaultCategoryDataset dataset=new DefaultCategoryDataset();
        SexualAssualtEval saeval=null;
        for(SexualAssualtEval e:eie.getAssualtDir().getLstevents())
        {
         saeval=e;
         //dataset.setValue(saeval.getCrimeAnalysisIndex(),"Marks","CrimeAnalysis");
         break;
        }
        if(saeval!=null)
        {
        dataset.setValue(saeval.getCrimeAnalysisIndex(),"Marks","CrimeAnalysis");
        dataset.setValue(saeval.getNatureAnalysis(),"Marks","NatureAnalysis");
        dataset.setValue(saeval.getSocialThreatIndex(),"Marks","SocialThreatIndex");
        dataset.setValue(saeval.getTestResults(),"Marks","TestResults");
        JFreeChart chart=ChartFactory.createBarChart("Sexual Assault evaluation","Factors", "Values", dataset,PlotOrientation.VERTICAL,false,true,false);
        CategoryPlot p=chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.BLACK);
        ChartFrame frame=new ChartFrame("Bar Chart for student",chart);
        frame.setVisible(true);
        frame.setSize(350,250);
        }
       
       
       
       
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> popCombo;
    // End of variables declaration//GEN-END:variables
}
