/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.FamilyCareWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SuicideAwarenessEnterprise;

import Business.Organization.FamilyCareOrganization;
import Business.SuicidePrevention.Event;
import Business.User.UserAccount;
import Business.WorkRequest.WorkRequest;
import Business.WorkRequest.WorkResponse;
import java.awt.CardLayout;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Chaitanya
 */
public class BackgroundCheckJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BackgroundCheckJPanel
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private FamilyCareOrganization organization;
    private Enterprise etrp;
    private EcoSystem business;
    private WorkResponse wr;
    
    public BackgroundCheckJPanel(JPanel userProcessContainer,WorkRequest wr, UserAccount account, FamilyCareOrganization organization, Enterprise etrp, EcoSystem business) {
        initComponents();
       this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.organization=organization;
        this.etrp=etrp;
        this.business=business;
        this.wr=(WorkResponse) wr;
       // populateWorkRequesst();
      // compute();
    }

    
    public void compute()
    {
     // ButtonModel bm1=q1rbg.getSelection();
     //bm1.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        q1rbg = new javax.swing.ButtonGroup();
        q2rbg = new javax.swing.ButtonGroup();
        q3rbg = new javax.swing.ButtonGroup();
        q4rbg = new javax.swing.ButtonGroup();
        q5rbg = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        q1Yes = new javax.swing.JRadioButton();
        q1No = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        q2Yes = new javax.swing.JRadioButton();
        q2No = new javax.swing.JRadioButton();
        q3Yes = new javax.swing.JRadioButton();
        q3No = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        q4Yes = new javax.swing.JRadioButton();
        q4No = new javax.swing.JRadioButton();
        q5Yes = new javax.swing.JRadioButton();
        q5No = new javax.swing.JRadioButton();
        btnCompute = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Has there been a occurrence of a stressfull event such as death, divorce, job loss?");

        q1rbg.add(q1Yes);
        q1Yes.setText("Yes");

        q1rbg.add(q1No);
        q1No.setText("No");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Does the patient have access to lethal firearms in your family ?");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Has the person been subjected to another person's suicide or graphic or sensationalized accounts of suicide?");

        q2rbg.add(q2Yes);
        q2Yes.setText("Yes");

        q2rbg.add(q2No);
        q2No.setText("No");

        q3rbg.add(q3Yes);
        q3Yes.setText("Yes");

        q3rbg.add(q3No);
        q3No.setText("No");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Has the patient attempted suicide before?");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Is there family history of suicides? ");

        q4Yes.setText("Yes");

        q4No.setText("No");

        q5Yes.setText("Yes");

        q5No.setText("No");

        btnCompute.setText("Proceed");
        btnCompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputeActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Background Check Questionnaire");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCompute))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 894, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(q5Yes)
                            .addComponent(q3Yes)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(q2Yes)
                                .addComponent(q1Yes))
                            .addComponent(q4Yes))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q1No)
                            .addComponent(q2No)
                            .addComponent(q3No)
                            .addComponent(q4No)
                            .addComponent(q5No))))
                .addGap(223, 223, 223))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q1Yes)
                            .addComponent(q1No))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q2No)
                            .addComponent(q2Yes))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q3Yes)
                            .addComponent(q3No))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q4Yes)
                            .addComponent(q4No))
                        .addGap(53, 53, 53))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(q5Yes)
                        .addComponent(q5No)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addComponent(btnCompute))
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout)userProcessContainer.getLayout()).previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnComputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputeActionPerformed
        // TODO add your handling code here:
        int count=0;
        //SuicideAwarenessEnterprise sae=(SuicideAwarenessEnterprise) etrp;
        if(wr.isIsComplete())
        {
            JOptionPane.showMessageDialog(null,"This request has already been completed","WARNING",JOptionPane.WARNING_MESSAGE);
            return;     
        }   
        
        
        if(!q1Yes.isSelected() && !q1No.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question one","WARNING",JOptionPane.WARNING_MESSAGE);
            return;   
        }
        if(!q2Yes.isSelected() && !q2No.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question two","WARNING",JOptionPane.WARNING_MESSAGE);
            return;   
        }
        if(!q3Yes.isSelected() && !q3No.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question three","WARNING",JOptionPane.WARNING_MESSAGE);
            return;   
        }
        if(!q4Yes.isSelected() && !q4No.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question four","WARNING",JOptionPane.WARNING_MESSAGE);
            return;   
        }
        if(!q5Yes.isSelected() && !q5No.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please answer question five","WARNING",JOptionPane.WARNING_MESSAGE);
            return;   
        }
        
        if(q1Yes.isSelected())
        {
           count++ ;
        }
        if(q2Yes.isSelected())
        {
           count++ ; 
        }
        if(q3Yes.isSelected())
        {
           count++ ; 
        }
        if(q4Yes.isSelected())
        {
           count++ ; 
        }
        if(q5Yes.isSelected())
        {
           count++ ; 
        }
        Event eve=(Event) wr.getResult()[0];
        if(eve!=null)
        {
        int sum=eve.getSeObj().getEnvironmentalFactors();
        sum=sum+count*5;
        eve.getSeObj().setEnvironmentalFactors(sum);
        }
        //wr.setReceiver(null);
        wr.setIsComplete(true);
        
        JOptionPane.showMessageDialog(null,"Request completed and sent back to Suicide Prevention enterprise");
        
        
    }//GEN-LAST:event_btnComputeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCompute;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton q1No;
    private javax.swing.JRadioButton q1Yes;
    private javax.swing.ButtonGroup q1rbg;
    private javax.swing.JRadioButton q2No;
    private javax.swing.JRadioButton q2Yes;
    private javax.swing.ButtonGroup q2rbg;
    private javax.swing.JRadioButton q3No;
    private javax.swing.JRadioButton q3Yes;
    private javax.swing.ButtonGroup q3rbg;
    private javax.swing.JRadioButton q4No;
    private javax.swing.JRadioButton q4Yes;
    private javax.swing.ButtonGroup q4rbg;
    private javax.swing.JRadioButton q5No;
    private javax.swing.JRadioButton q5Yes;
    private javax.swing.ButtonGroup q5rbg;
    // End of variables declaration//GEN-END:variables
}
