/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DoctorWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.SuicidePrevention.Event;
import Business.User.UserAccount;
import Business.WorkRequest.WorkRequest;
import Business.WorkRequest.WorkResponse;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chaitanya
 */
public class ManageWorkRequestDoctor extends javax.swing.JPanel {

    /**
     * Creates new form ManageWorkRequestDoctor
     */
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private DoctorOrganization doctorOrganization;
    private Enterprise etrp;
    private EcoSystem business;
    
    public ManageWorkRequestDoctor(JPanel userProcessContainer, UserAccount account, DoctorOrganization doctorOrganization, Enterprise etrp, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.doctorOrganization=doctorOrganization;
        this.etrp=etrp;
        this.business=business;
        populateWorkReq();
    }
    public void populateWorkReq()
    {
        DefaultTableModel dtm=(DefaultTableModel) tblWorkReq.getModel();
        dtm.setRowCount(0);
        for(WorkRequest wr:doctorOrganization.getWorkQueue().getLstWorkRequest())
        {
           Object[] row=new Object[4];
           row[0]=wr;
           row[1]=wr.getPerson();
           row[2]=wr.getStatus();
           row[3]=wr.getReceiver()==null?"UnAssigned":wr.getReceiver();
           dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblWorkReq = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        btnProcess = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Manage Work Requests");

        tblWorkReq.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Work Request", "Person", "Status", "Receiver"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblWorkReq);

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAssign.setText("Assign");
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnProcess.setText("Process");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBack)
                            .addGap(244, 244, 244)
                            .addComponent(btnAssign)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProcess))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 786, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnProcess)
                    .addComponent(btnAssign))
                .addContainerGap(230, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout)userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        int selectedRow=tblWorkReq.getSelectedRow();
        if(selectedRow>-1)
        {
            WorkRequest wr=(WorkRequest) tblWorkReq.getValueAt(selectedRow,0);
            if(!wr.getOl().equals(WorkRequest.OperationalLevel.Doctor))
            {
                JOptionPane.showMessageDialog(null,"Request is being serviced at "+wr.getOl().name() +" operational level","WARNING",JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(wr.getReceiver()!=null && wr.getReceiver()!=account)
            {
                JOptionPane.showMessageDialog(null,"Request is assigned to some other user","WARNING",JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(wr.getReceiver()==account)
            {

                JOptionPane.showMessageDialog(null,"Request already assigned to current user","WARNING",JOptionPane.WARNING_MESSAGE);
                return;
            }

            wr.setReceiver(account);
            // wr.setOl(WorkRequest.OperationalLevel.Lab);
            JOptionPane.showMessageDialog(null,"Request id - "+wr.getRequestId()+" has been assigned to you!");
            populateWorkReq();

        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select a request from table","WARNING",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnAssignActionPerformed

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:
        int selectedRow=tblWorkReq.getSelectedRow();
        if(selectedRow>-1)
        {
            WorkResponse wr=(WorkResponse) tblWorkReq.getValueAt(selectedRow,0);
            if(wr!=null)
            {
                if(!wr.getOl().equals(WorkRequest.OperationalLevel.Doctor))
                {
                    JOptionPane.showMessageDialog(null,"Request is being serviced at "+wr.getOl().name() +" operational level","WARNING",JOptionPane.WARNING_MESSAGE);
                    return;
                }
                if(wr.getReceiver()!=account)
                {
                    JOptionPane.showMessageDialog(null,"Request is not assigned to current user","WARNING",JOptionPane.WARNING_MESSAGE);
                    return;
                }
                if(wr.getRtype().equals(WorkResponse.RequestType.SuicidePrevention))
                {
                    //Event eve=(Event) wr.getResult()[0];
                    
                    if(wr.getPerson().getItr()==1)
                    {
                userProcessContainer.add(new PatientTreatmentJPanel(userProcessContainer, account, doctorOrganization, etrp, business,wr));
                ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
                
                    }
                    else
                    {
                     userProcessContainer.add(new PatientTreatmentItrJPanel(userProcessContainer, account, doctorOrganization, etrp, business,wr));
                ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);   
                    }
                    
                    //JOptionPane.showMessageDialog(null,"Sorry!No event found");
                }
                else if (wr.getRtype().equals(WorkResponse.RequestType.DrugAbusePrevention))
                {
                   wr.setIsComplete(true);
                   wr.setReceiver(account);
                   wr.setStatus("Completed");
                   JOptionPane.showMessageDialog(null, "Person is being treated by doctor!!");
                   populateWorkReq();
                }
                
//                SuicideAwarenessEnterprise sae=null;
//                DrugFreeEnterprise dre = null;
//                if(wr.getRtype().equals(WorkRequest.RequestType.SuicidePrevention))
//                {
//                    for(Network net :system.getNetworkDir().getLstNetwork())
//                    {
//                        for(Enterprise etr:net.getEnterpriseDir().getLstEnterprises())
//                        {
//                            if(etr.getEt().equals(Enterprise.ErpType.SuicideAwareness))
//                            {
//                                sae=(SuicideAwarenessEnterprise) etr;
//                                break;
//                            }
//                        }
//                        if(sae!=null)
//                        {
//                            break;
//                        }
//                    }
//                    if(sae!=null)
//                    {
//                        wr.setReceiver(null);
//                        wr.setOl(WorkRequest.OperationalLevel.SP);
//                        wr.setStatus("Pending-Request sent to Suicide Prevention Enterprise");
//                        ua.getWorkQueue().getLstWorkRequest().add(wr);
//                        sae.getWorkQueue().getLstWorkRequest().add(wr);
//                        JOptionPane.showMessageDialog(null,"Request sent to Suicide Prevention");
//                        populateWorkRequest();
//                    }
//                }
//                else
//                {
//                    for(Network net :system.getNetworkDir().getLstNetwork())
//                    {
//                        for(Enterprise etr:net.getEnterpriseDir().getLstEnterprises())
//                        {
//                            if(etr.getEt().equals(Enterprise.ErpType.DrugFree))
//                            {
//                                dre=(DrugFreeEnterprise) etr;
//                                break;
//                            }
//                        }
//                        if(dre!=null)
//                        {
//                            break;
//                        }
//                    }
//                    if(dre!=null)
//                    {
//                        wr.setReceiver(null);
//                        wr.setOl(WorkRequest.OperationalLevel.DrugFree); //to put enterprises and organizations in operational level
//                        dre.getWorkQueue().getLstWorkRequest().add(wr);
//                        String priority="Medium";
//                        Object[] obj=new Object[2];
//                        obj[0]=priority;
//                        obj[1]=true;
//                        wr.setResult(obj);
//                        ua.getWorkQueue().getLstWorkRequest().add(wr);
//                        wr.setStatus("Pending-Request sent to Drug Free Enterprise");
//                        JOptionPane.showMessageDialog(null,"Request sent to Drug Free Enterprise");
//                        populateWorkRequest();
//                    }
//
//                }
                //

            }
        }
        else
        {
            JOptionPane.showMessageDialog(null,"Please select a row from table","WARNING",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnProcessActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblWorkReq;
    // End of variables declaration//GEN-END:variables
}
