/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.DoctorWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.MedicalRecord.MedicalRecord;
import Business.Organization.DoctorOrganization;
import Business.Person.Person;
import Business.SuicidePrevention.Event;
import Business.User.UserAccount;
import Business.WorkRequest.WorkResponse;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Chaitanya
 */
public class PatientTreatmentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientTreatmentJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private DoctorOrganization doctorOrganization;
    private Enterprise etrp;
    private EcoSystem business;
    private WorkResponse wr;
    private MedicalRecord mr=null;
    private HospitalEnterprise he=null;
    public PatientTreatmentJPanel(JPanel userProcessContainer, UserAccount account, DoctorOrganization doctorOrganization, Enterprise etrp, EcoSystem business, WorkResponse wr) {
       initComponents();
       
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.doctorOrganization=doctorOrganization;
        this.etrp=etrp;
        this.business=business;
        this.wr=wr;
        populatePatientDetails();
    }
    public void populatePatientDetails()
    {
     txtPersonName.setText(wr.getPerson().getPersonName());
     txtEmailId.setText(wr.getPerson().getEmail());
     txtContactNo.setText(Long.toString(wr.getPerson().getPhoneNo()));
     txtDob.setText(wr.getPerson().getDateOfBirth().toString());
     //
     //JFileChooser jc = new JFileChooser();
       // jc.showOpenDialog(null);
        //File f = jc.getSelectedFile();
        //String fn = f.getAbsolutePath()
        //picAddress.setText(fn);
        String path=wr.getPerson().getProfilePhoto();
        ImageIcon i = new ImageIcon(path);
        //labelname.setIcon(icon);
        displaypic.setIcon(i);
     //
     if(wr.getPerson().getGender().equals(Person.Gender.Male))
     {
         rblMaleGender.setSelected(true);
     }
     else
     {
         rblFemaleGender.setSelected(true);
     }
//        SimpleDateFormat sf=new SimpleDateFormat("MM-dd-yyyy");
//     Date d=wr.getPerson().getDateOfBirth();
//     txtDob.setText(sf.format(d));
     he=(HospitalEnterprise) etrp;
     //txtEmailId.setText(wr.getPerson());
     for(MedicalRecord mrd:he.getMedicalRecordDir().getLstMedicalRecord())
     {
         if(mrd.getPerson()==wr.getPerson())
         {
             mr=mrd;
             break;
         }
     }
     if(mr!=null)
     {
         txtBloodPressure.setText(mr.getVitalSign().getHighbloodPressure()+" - "+mr.getVitalSign().getLowBloodPressure());
         txtHeartRate.setText(Integer.toString(mr.getVitalSign().getHeartRate()));
         txtDrugTest.setText(Float.toString(mr.getDrugTestResults()));
         txtAlcoholResults.setText(Float.toString(mr.getAlcoholResults()));
         
     }
     
     
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtPersonName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rblMaleGender = new javax.swing.JRadioButton();
        rblFemaleGender = new javax.swing.JRadioButton();
        displaypic = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtDob = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtBloodPressure = new javax.swing.JTextField();
        txtHeartRate = new javax.swing.JTextField();
        txtDrugTest = new javax.swing.JTextField();
        txtAlcoholResults = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        chkAnxDis = new javax.swing.JCheckBox();
        chkPsy = new javax.swing.JCheckBox();
        chkBipDis = new javax.swing.JCheckBox();
        chkSchizo = new javax.swing.JCheckBox();
        chkDep = new javax.swing.JCheckBox();
        chkChronic = new javax.swing.JCheckBox();
        chkLung = new javax.swing.JCheckBox();
        ChkAnx = new javax.swing.JCheckBox();
        chkCancer = new javax.swing.JCheckBox();
        btnPrognose = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPrescription = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Information"));

        txtPersonName.setEnabled(false);
        txtPersonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPersonNameActionPerformed(evt);
            }
        });

        jLabel1.setText("Name:");

        jLabel3.setText("Gender:");

        rblMaleGender.setText("Male");
        rblMaleGender.setEnabled(false);
        rblMaleGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblMaleGenderActionPerformed(evt);
            }
        });

        rblFemaleGender.setText("Female");
        rblFemaleGender.setEnabled(false);
        rblFemaleGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblFemaleGenderActionPerformed(evt);
            }
        });

        displaypic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setText("Email ID:");

        txtEmailId.setEnabled(false);
        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });

        jLabel6.setText("Contact No:");

        txtContactNo.setEnabled(false);
        txtContactNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactNoActionPerformed(evt);
            }
        });

        jLabel13.setText("D.O.B");

        txtDob.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(displaypic, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rblMaleGender, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rblFemaleGender))
                    .addComponent(txtEmailId)
                    .addComponent(txtContactNo, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addComponent(txtPersonName)
                    .addComponent(txtDob))
                .addGap(18, 18, 18)
                .addComponent(jLabel2))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displaypic, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtPersonName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(rblMaleGender)
                            .addComponent(rblFemaleGender))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEmailId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtDob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Vital Signs"));

        jLabel7.setText("BloodPressure:");

        jLabel8.setText("HeartRate:");

        jLabel9.setText("Drug Test:");

        jLabel10.setText("Alcohol Test:");

        txtBloodPressure.setEnabled(false);

        txtHeartRate.setEnabled(false);

        txtDrugTest.setEnabled(false);

        txtAlcoholResults.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAlcoholResults, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(txtDrugTest)
                    .addComponent(txtBloodPressure)
                    .addComponent(txtHeartRate))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDrugTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtAlcoholResults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Symptoms and Ailments"));

        jLabel11.setText("Symptoms:");

        jLabel12.setText("Please check the ailments applicable:");

        chkAnxDis.setText("Anxiety Disorder");

        chkPsy.setText("Psychotic Disorder");

        chkBipDis.setText("BipolarDisorder");

        chkSchizo.setText("Schizophrenia");

        chkDep.setText("Depression");

        chkChronic.setText("Chronic pain");

        chkLung.setText("Lung disease");

        ChkAnx.setText("Anxiety");

        chkCancer.setText("Cancer");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkBipDis)
                            .addComponent(chkSchizo))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAnxDis)
                            .addComponent(chkDep))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkCancer)
                            .addComponent(chkPsy)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkChronic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(chkLung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChkAnx))
                    .addComponent(jLabel12))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(chkChronic)
                    .addComponent(chkLung)
                    .addComponent(ChkAnx))
                .addGap(59, 59, 59)
                .addComponent(jLabel12)
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkSchizo)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(chkDep)
                        .addComponent(chkCancer)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkAnxDis)
                    .addComponent(chkPsy)
                    .addComponent(chkBipDis))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnPrognose.setText("Prognose");
        btnPrognose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrognoseActionPerformed(evt);
            }
        });

        txtPrescription.setColumns(20);
        txtPrescription.setRows(5);
        jScrollPane2.setViewportView(txtPrescription);

        jLabel14.setText("Notes/Prescription:");

        jLabel15.setText("PATIENT PROFILE");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Hi,\nHow are feeling today?\n");
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(41, 41, 41))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addGap(139, 139, 139)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPrognose)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btnPrognose)
                        .addGap(49, 49, 49))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPersonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPersonNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPersonNameActionPerformed

    private void rblMaleGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblMaleGenderActionPerformed
        // TODO add your handling code here:
        rblFemaleGender.setSelected(false);
    }//GEN-LAST:event_rblMaleGenderActionPerformed

    private void rblFemaleGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblFemaleGenderActionPerformed
        // TODO add your handling code here:
        rblMaleGender.setSelected(false);
    }//GEN-LAST:event_rblFemaleGenderActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void txtContactNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactNoActionPerformed

    private void btnPrognoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrognoseActionPerformed
        // TODO add your handling code here:
        if(!wr.getOl().equals(WorkResponse.OperationalLevel.Doctor))
       {
           JOptionPane.showMessageDialog(null,"Request is being serviced at "+wr.getOl().name() +" operational level","WARNING",JOptionPane.WARNING_MESSAGE);       
           return;
       }
       if(wr.getReceiver()!=account)
       {
           JOptionPane.showMessageDialog(null,"This request does not belong to this account","WARNING",JOptionPane.WARNING_MESSAGE);
           return;
       }
       String pres=txtPrescription.getText();
       if(!pres.toString().matches("[A-Za-z 0-9]+"))
       {
         JOptionPane.showMessageDialog(null,"Please provide some medication/prescription","WARNING",JOptionPane.WARNING_MESSAGE);
           return;
       }
       Event eve=(Event) wr.getResult()[0];
       if(eve!=null)
       {
       inputHealthSymptoms(eve);
       inputHealthAilments(eve);
       normalizeVitals();
       }
        wr.setReceiver(null);
        account.getWorkQueue().getLstWorkRequest().add(wr);
        etrp.getWorkQueue().getLstWorkRequest().add(wr);
        wr.setOl(WorkResponse.OperationalLevel.Hospital);
        wr.setStatus("Pending - Sent to Hospital Admin");
        JOptionPane.showMessageDialog(null,"This patient needs to be further evaluated,Request sent to Hospital Enterprise");
        
    }//GEN-LAST:event_btnPrognoseActionPerformed
    public void inputHealthSymptoms(Event eve)
    {
        if(ChkAnx.isSelected())
        {
            mr.getSymptoms().add(ChkAnx.getText());
            
        }
        if(chkChronic.isSelected())
        {
            mr.getSymptoms().add(chkChronic.getText());
            
        }
        if(chkLung.isSelected())
        {
            mr.getSymptoms().add(chkLung.getText());
            
        }
        int size=mr.getSymptoms().size();
        int sum=eve.getSeObj().getHealthFactors();
        int healthfac=0;
        
            healthfac=size*2;
        
        sum=sum+healthfac;
        eve.getSeObj().setHealthFactors(sum);
        
    }
    public void inputHealthAilments(Event eve)
    {
        if(chkAnxDis.isSelected())
        {
            mr.getAilments().add(chkAnxDis.getText());
        }
        if(chkBipDis.isSelected())
        {
            mr.getAilments().add(chkBipDis.getText());
        }
        if(chkCancer.isSelected())
        {
            mr.getAilments().add(chkCancer.getText());
        }
        if(chkPsy.isSelected())
        {
            mr.getAilments().add(chkPsy.getText());
        }
        if(chkSchizo.isSelected())
        {
            mr.getAilments().add(chkSchizo.getText());
        }
        if(chkCancer.isSelected())
        {
            mr.getAilments().add(chkCancer.getText());
        }
        int size=mr.getAilments().size();
        int sum=eve.getSeObj().getHealthFactors();
        int healthfac=0;
        if(size>=3)
        {
            healthfac=size*1;
        }
        else
        {
           healthfac=size*2; 
        }
        sum=sum+healthfac;
        eve.getSeObj().setHealthFactors(sum);
    }
    public void normalizeVitals()
    {
       // int count=0;
      int hbp=0,lbp=0,hr=0;
        float dt=0.0f,at=0.0f;
        Random r=new Random();
        hbp=r.nextInt(120-100)+110;
        lbp=r.nextInt(90-80)+78;
        
        hr=r.nextInt(30)+86;
        
        at=(float) (0.01*(r.nextInt(8))+1);
        
        dt=(float) (0.01*(r.nextInt(8))+1);
        
        for(MedicalRecord mr:he.getMedicalRecordDir().getLstMedicalRecord())
            {
                if(mr.getPerson()==wr.getPerson())
                {
                   mr.getVitalSign().setHighbloodPressure(hbp);
                   mr.getVitalSign().setLowBloodPressure(lbp);
                   mr.getVitalSign().setHeartRate(hr);
                   mr.setAlcoholResults(at);
                   mr.setDrugTestResults(dt);
                   break;
                }
            }
        
        //eve.getSeObj().setVitalSignsFactor(count*3);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChkAnx;
    private javax.swing.JButton btnPrognose;
    private javax.swing.JCheckBox chkAnxDis;
    private javax.swing.JCheckBox chkBipDis;
    private javax.swing.JCheckBox chkCancer;
    private javax.swing.JCheckBox chkChronic;
    private javax.swing.JCheckBox chkDep;
    private javax.swing.JCheckBox chkLung;
    private javax.swing.JCheckBox chkPsy;
    private javax.swing.JCheckBox chkSchizo;
    private javax.swing.JLabel displaypic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton rblFemaleGender;
    private javax.swing.JRadioButton rblMaleGender;
    private javax.swing.JTextField txtAlcoholResults;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtDob;
    private javax.swing.JTextField txtDrugTest;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtPersonName;
    private javax.swing.JTextArea txtPrescription;
    // End of variables declaration//GEN-END:variables
}
