/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Reception;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.ReceptionistOrganization;
import Business.User.UserAccount;
import Interface.LabWorkArea.ManageWorkRequestJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Chaitanya
 */
public class ReceptionWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organisation;
    private Enterprise etrp;
    private EcoSystem business;
    public ReceptionWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, ReceptionistOrganization organisation, Enterprise etrp, EcoSystem business) {
        initComponents();
        this.business=business;
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.etrp=etrp;
        this.organisation=organisation;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerPatientBtn = new javax.swing.JButton();
        viewPatientBtn = new javax.swing.JButton();
        manageWorkReqBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        registerPatientBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        registerPatientBtn.setText("Register Patient");
        registerPatientBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        registerPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerPatientBtnActionPerformed(evt);
            }
        });

        viewPatientBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        viewPatientBtn.setText("View PatientCatalog");
        viewPatientBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        viewPatientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPatientBtnActionPerformed(evt);
            }
        });

        manageWorkReqBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        manageWorkReqBtn.setText("View Work Request");
        manageWorkReqBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        manageWorkReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageWorkReqBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Reception Work Area");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(347, 347, 347)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(registerPatientBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewPatientBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                            .addComponent(manageWorkReqBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(320, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(52, 52, 52)
                .addComponent(registerPatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(viewPatientBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(manageWorkReqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPatientBtnActionPerformed
         userProcessContainer.add("ViewPatientCatalogJPanel",new ViewPatientCatalogJPanel(userProcessContainer,account,organisation,etrp,business));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_viewPatientBtnActionPerformed

    private void registerPatientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerPatientBtnActionPerformed

//       userProcessContainer.add("RegisterPatientJPanel",new RegisterPatientJPanel(userProcessContainer,account,organisation,etrp,business));
//        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);

      // userProcessContainer.add("RegisterPatientJPanel",new RegisterPatientJPanel(userProcessContainer,account,organisation,etrp,business));
      //  ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
       userProcessContainer.add("RegisterPatientJPanel",new RegisterPatientJPanel(userProcessContainer,account,organisation,etrp,business));
       ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);

    }//GEN-LAST:event_registerPatientBtnActionPerformed

    private void manageWorkReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageWorkReqBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.add(new ViewWorkRequestJPanel(userProcessContainer, account, organisation, etrp, business));
                ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_manageWorkReqBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageWorkReqBtn;
    private javax.swing.JButton registerPatientBtn;
    private javax.swing.JButton viewPatientBtn;
    // End of variables declaration//GEN-END:variables
}
