/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.ProctorWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.CitizenComplaintOrganization;
import Business.User.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Chaitanya
 */
public class ProctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProctorWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private CitizenComplaintOrganization citizenComplaintOrg;
    private Enterprise etrp;
    private EcoSystem business;
    

    public ProctorWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CitizenComplaintOrganization citizenComplaintOrganization, Enterprise etrp, EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.citizenComplaintOrg=citizenComplaintOrganization;
        this.etrp=etrp;
        this.business=business;
                
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageProctorWorkRequest = new javax.swing.JButton();

        btnManageProctorWorkRequest.setText("ManageProctorWorkRequest");
        btnManageProctorWorkRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProctorWorkRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(btnManageProctorWorkRequest)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnManageProctorWorkRequest)
                .addContainerGap(179, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageProctorWorkRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProctorWorkRequestActionPerformed
        // TODO add your handling code here:
        userProcessContainer.add(new ManageProctorWorkRequestJPanel(userProcessContainer, account, citizenComplaintOrg, etrp, business));
                ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);

    }//GEN-LAST:event_btnManageProctorWorkRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageProctorWorkRequest;
    // End of variables declaration//GEN-END:variables
}
