/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SuicideAwarenessWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.SuicideAwarenessOrganization;
import Business.SuicidePrevention.Event;
import Business.User.UserAccount;
import Business.WorkRequest.WorkRequest;
import Business.WorkRequest.WorkResponse;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Chaitanya
 */
public class BehavioralRiskJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BehavioralRiskJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private SuicideAwarenessOrganization suiAwaOrg;
    private Enterprise etrp;
    private EcoSystem business;
    private WorkResponse wr;

    public BehavioralRiskJPanel(JPanel userProcessContainer, UserAccount account, Enterprise etrp, SuicideAwarenessOrganization suiAwaOrg, EcoSystem business, WorkResponse wr) {
        initComponents();
         this.userProcessContainer=userProcessContainer;
         this.account=account;
         this.suiAwaOrg=suiAwaOrg;
         this.etrp=etrp;
         this.business=business;
         this.wr=wr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        q1Yes = new javax.swing.JRadioButton();
        q1No = new javax.swing.JRadioButton();
        q2Yes = new javax.swing.JRadioButton();
        q2No = new javax.swing.JRadioButton();
        q3Yes = new javax.swing.JRadioButton();
        q3No = new javax.swing.JRadioButton();
        q4Yes = new javax.swing.JRadioButton();
        q4No = new javax.swing.JRadioButton();
        q5No = new javax.swing.JRadioButton();
        q5Yes = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Do you feel like being a burden to Others?");

        buttonGroup1.add(q1Yes);
        q1Yes.setText("Yes");

        buttonGroup1.add(q1No);
        q1No.setText("No");

        buttonGroup2.add(q2Yes);
        q2Yes.setText("Yes");

        buttonGroup2.add(q2No);
        q2No.setText("No");

        buttonGroup3.add(q3Yes);
        q3Yes.setText("Yes");

        buttonGroup3.add(q3No);
        q3No.setText("No");

        buttonGroup4.add(q4Yes);
        q4Yes.setText("Yes");

        buttonGroup4.add(q4No);
        q4No.setText("No");

        buttonGroup5.add(q5No);
        q5No.setText("No");

        buttonGroup5.add(q5Yes);
        q5Yes.setText("Yes");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Is there family history of suicides? ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Do you constantly feel the need to kill yourself?");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Do you feel  like having no reason to live?");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Do you feel like being trapped?");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setText("BehavioralFactors");

        btnNext.setText("Next>>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(283, 283, 283)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(q2Yes)
                    .addComponent(q1Yes)
                    .addComponent(q3Yes)
                    .addComponent(q4Yes)
                    .addComponent(q5Yes))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q2No)
                            .addComponent(q1No)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q4No)
                            .addComponent(q3No)
                            .addComponent(q5No))))
                .addGap(356, 356, 356))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(533, 533, 533)
                        .addComponent(btnNext)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel5)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q1Yes)
                            .addComponent(q1No))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q2Yes)
                            .addComponent(q2No))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q3Yes)
                            .addComponent(q3No))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q4Yes)
                            .addComponent(q4No))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q5Yes)
                            .addComponent(q5No))))
                .addGap(128, 128, 128)
                .addComponent(btnNext)
                .addGap(169, 169, 169))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        int count=0;
        //SuicideAwarenessEnterprise sae=(SuicideAwarenessEnterprise) etrp;
            if(wr.isIsComplete())
                {
                JOptionPane.showMessageDialog(null,"Request is already completed"+wr.getOl().name() +" operational level","WARNING",JOptionPane.WARNING_MESSAGE);
                return;
                }
            if(!wr.getOl().equals(WorkRequest.OperationalLevel.SA))
            {
                JOptionPane.showMessageDialog(null,"Request is being serviced at "+wr.getOl().name() +" operational level","WARNING",JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(wr.getReceiver()!=null && wr.getReceiver()!=account)
            {
                JOptionPane.showMessageDialog(null,"Request is assigned to some other user","WARNING",JOptionPane.WARNING_MESSAGE);
                return;
            }
        if(!q1Yes.isSelected() && !q1No.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please select atleast one option","WARNING",JOptionPane.WARNING_MESSAGE);
            return;   
        }
        if(!q2Yes.isSelected() && !q2No.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please select atleast one option","WARNING",JOptionPane.WARNING_MESSAGE);
            return;   
        }
        if(!q3Yes.isSelected() && !q3No.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please select atleast one option","WARNING",JOptionPane.WARNING_MESSAGE);
            return;   
        }
        if(!q4Yes.isSelected() && !q4No.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please select atleast one option","WARNING",JOptionPane.WARNING_MESSAGE);
            return;   
        }
        if(!q5Yes.isSelected() && !q5No.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please select atleast one option","WARNING",JOptionPane.WARNING_MESSAGE);
            return;   
        }
        if(q1Yes.isSelected())
        {
           count++ ;
        }
        if(q2Yes.isSelected())
        {
           count++ ; 
        }
        if(q3Yes.isSelected())
        {
           count++ ; 
        }
        if(q4Yes.isSelected())
        {
           count++ ; 
        }
        if(q5Yes.isSelected())
        {
           count++ ; 
        }
        Event eve=(Event) wr.getResult()[0];
        if(eve!=null)
        {
        int sum=eve.getSeObj().getHistoricalFactors();
        sum=sum+count*3;
        eve.getSeObj().setHistoricalFactors(sum);
        //TODO
        userProcessContainer.add(new MoodAndBehavioralJPanel(userProcessContainer,account,etrp,suiAwaOrg,business,wr));
        ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
        }
    }//GEN-LAST:event_btnNextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton q1No;
    private javax.swing.JRadioButton q1Yes;
    private javax.swing.JRadioButton q2No;
    private javax.swing.JRadioButton q2Yes;
    private javax.swing.JRadioButton q3No;
    private javax.swing.JRadioButton q3Yes;
    private javax.swing.JRadioButton q4No;
    private javax.swing.JRadioButton q4Yes;
    private javax.swing.JRadioButton q5No;
    private javax.swing.JRadioButton q5Yes;
    // End of variables declaration//GEN-END:variables
}
