/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SuicideAwarenessWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.SuicideAwarenessEnterprise;
import Business.Organization.SuicideAwarenessOrganization;
import Business.Person.Person;
import Business.SuicidePrevention.Event;
import Business.User.UserAccount;
import Business.WorkRequest.WorkRequest;
import Business.WorkRequest.WorkResponse;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Chaitanya
 */
public class MoodAndBehavioralJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MoodAndBehavioralJPanel
     */
    private JPanel userProcessContainer;
    private UserAccount account;
    private SuicideAwarenessOrganization suiAwaOrg;
    private Enterprise etrp;
    private EcoSystem business;
    private WorkResponse wr;
    private SuicideAwarenessEnterprise sae=null;

    public MoodAndBehavioralJPanel(JPanel userProcessContainer, UserAccount account, Enterprise etrp, SuicideAwarenessOrganization suiAwaOrg, EcoSystem business, WorkResponse wr) {
        initComponents();
         this.userProcessContainer=userProcessContainer;
         this.account=account;
         this.suiAwaOrg=suiAwaOrg;
         this.etrp=etrp;
         this.business=business;
         this.wr=wr;
         sae=(SuicideAwarenessEnterprise) etrp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        q1Yes = new javax.swing.JRadioButton();
        q1No = new javax.swing.JRadioButton();
        q2Yes = new javax.swing.JRadioButton();
        q2No = new javax.swing.JRadioButton();
        q3Yes = new javax.swing.JRadioButton();
        q3No = new javax.swing.JRadioButton();
        q4Yes = new javax.swing.JRadioButton();
        q4No = new javax.swing.JRadioButton();
        q5Yes = new javax.swing.JRadioButton();
        q5No = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btnComplete = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("Talk Check Questions");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("Having you been visiting or calling people to say goodbye");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Have you been sleeping too little or too much");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Do you see increased use of alcohol or drugs");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Do you feel a sense of withdrawal from everything?");

        buttonGroup1.add(q1Yes);
        q1Yes.setText("Yes");

        buttonGroup1.add(q1No);
        q1No.setText("No");

        buttonGroup2.add(q2Yes);
        q2Yes.setText("Yes");

        buttonGroup2.add(q2No);
        q2No.setText("No");

        buttonGroup3.add(q3Yes);
        q3Yes.setText("Yes");

        buttonGroup3.add(q3No);
        q3No.setText("No");

        buttonGroup4.add(q4Yes);
        q4Yes.setText("Yes");

        buttonGroup4.add(q4No);
        q4No.setText("No");

        buttonGroup5.add(q5Yes);
        q5Yes.setText("Yes");

        buttonGroup5.add(q5No);
        q5No.setText("No");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Have been giving away your prized possessions?");

        btnComplete.setText("Complete Profile");
        btnComplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(837, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(346, 346, 346)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q5Yes)
                                .addGap(29, 29, 29)
                                .addComponent(q5No))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(q4Yes)
                                .addGap(29, 29, 29)
                                .addComponent(q4No))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(q3Yes)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(q3No))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(q1Yes)
                                    .addGap(29, 29, 29)
                                    .addComponent(q1No))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(q2Yes)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(q2No))))
                        .addGap(227, 227, 227))))
            .addGroup(layout.createSequentialGroup()
                .addGap(550, 550, 550)
                .addComponent(btnComplete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(415, 415, 415))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel4)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q1No)
                            .addComponent(q1Yes))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q2Yes)
                            .addComponent(q2No))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q3Yes)
                            .addComponent(q3No))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q4Yes)
                            .addComponent(q4No))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(q5No)
                            .addComponent(q5Yes))))
                .addGap(94, 94, 94)
                .addComponent(btnComplete)
                .addGap(291, 291, 291))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteActionPerformed
        // TODO add your handling code here:
        int count=0;
        //SuicideAwarenessEnterprise sae=(SuicideAwarenessEnterprise) etrp;
                if(wr.isIsComplete())
                {
                JOptionPane.showMessageDialog(null,"Request is already completed","WARNING",JOptionPane.WARNING_MESSAGE);
                return;
                }
            if(!wr.getOl().equals(WorkRequest.OperationalLevel.SA))
            {
                JOptionPane.showMessageDialog(null,"Request is being serviced at "+wr.getOl().name() +" operational level","WARNING",JOptionPane.WARNING_MESSAGE);
                return;
            }
            if(wr.getReceiver()!=null && wr.getReceiver()!=account)
            {
                JOptionPane.showMessageDialog(null,"Request is assigned to some other user","WARNING",JOptionPane.WARNING_MESSAGE);
                return;
            }
        if(!q1Yes.isSelected() && !q1No.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please select atleast one option","WARNING",JOptionPane.WARNING_MESSAGE);
            return;   
        }
        if(!q2Yes.isSelected() && !q2No.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please select atleast one option","WARNING",JOptionPane.WARNING_MESSAGE);
            return;   
        }
        if(!q3Yes.isSelected() && !q3No.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please select atleast one option","WARNING",JOptionPane.WARNING_MESSAGE);
            return;   
        }
        if(!q4Yes.isSelected() && !q4No.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please select atleast one option","WARNING",JOptionPane.WARNING_MESSAGE);
            return;   
        }
        if(!q5Yes.isSelected() && !q5No.isSelected())
        {
            JOptionPane.showMessageDialog(null,"Please select atleast one option","WARNING",JOptionPane.WARNING_MESSAGE);
            return;   
        }
        if(q1Yes.isSelected())
        {
           count++ ;
        }
        if(q2Yes.isSelected())
        {
           count++ ; 
        }
        if(q3Yes.isSelected())
        {
           count++ ; 
        }
        if(q4Yes.isSelected())
        {
           count++ ; 
        }
        if(q5Yes.isSelected())
        {
           count++ ; 
        }
        Event eve=(Event) wr.getResult()[0];
        if(eve!=null)
        {
        int sum=eve.getSeObj().getHistoricalFactors();
        sum=sum+count*2;
        eve.getSeObj().setHistoricalFactors(sum);
        eve.getSeObj().CalculateSuicideThreatIndex();
        //Person perFound=null;
        //boolean found=false;
        ArrayList<Event> lstFoundEvent=null;
        for(Map.Entry<Person,ArrayList<Event>> va :sae.getReport().getTmSuicideReport().entrySet())
        {
          if(va.getKey()==wr.getPerson())
          {
              //found=true;
              //perFound=va.getKey();
               lstFoundEvent=va.getValue();
          }
        }
        if(lstFoundEvent!=null)
        {
           lstFoundEvent.add(eve);
            sendAlert(lstFoundEvent, eve, wr.getPerson());
        }
        else
        {
          ArrayList<Event> lstEvents=sae.getReport().getEventList(); 
          lstEvents.add(eve);
          //
          //  sendAlert(lstEvents, eve, wr.getPerson());
          //
          
          sae.getReport().createReport(wr.getPerson(),lstEvents); 
        }
        
        wr.setIsComplete(true);
        wr.setStatus("Request Completed");
        wr.getPerson().setAvailable(true);
        
        JOptionPane.showMessageDialog(null,"Person has been registered in suicide awereness organization and all request have been completed");
        //lstEvents.add(eve);
        
       // ArrayList<Event> lstEvents=sae.getReport().getEventList();
       // lstEvents.add(eve);
       // sae.getReport().createReport(wr.getPerson(),lstEvents);
        
        //TODO
        //userProcessContainer.add(new MoodAndBehavioralJPanel(userProcessContainer,account,etrp,suiAwaOrg,business,wr));
        //((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
        }
        
    }//GEN-LAST:event_btnCompleteActionPerformed
    public void sendAlert(ArrayList<Event> lstEvent,Event evt,Person pt)
    {
        Event eventPrev=null;
        Event eventNext=evt;
        for(int i =0;i<lstEvent.size();i++)
        {
            if(lstEvent.get(i)==eventNext)
            {
                eventPrev=lstEvent.get(i-1); 
                if(eventPrev!=null)
                {
                if(eventNext.getSeObj().getSuicideThreatIndex()>eventPrev.getSeObj().getSuicideThreatIndex())
                {
                    //do something;
                   // JOptionPane.showMessageDialog(null,"Alert sent");
                    int diff=eventNext.getSeObj().getSuicideThreatIndex()-eventPrev.getSeObj().getSuicideThreatIndex();
                    sae.getReport().getLstAlerts().add("Suicide threat index increased by "+diff+" for person "+pt.getPersonName());
                }
                }
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComplete;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton q1No;
    private javax.swing.JRadioButton q1Yes;
    private javax.swing.JRadioButton q2No;
    private javax.swing.JRadioButton q2Yes;
    private javax.swing.JRadioButton q3No;
    private javax.swing.JRadioButton q3Yes;
    private javax.swing.JRadioButton q4No;
    private javax.swing.JRadioButton q4Yes;
    private javax.swing.JRadioButton q5No;
    private javax.swing.JRadioButton q5Yes;
    // End of variables declaration//GEN-END:variables
}
