/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.LabWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.LabOrganization;
import Business.Organization.Organization;
import Business.Person.Person;
import Business.User.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Chaitanya
 */
public class ViewPatientCatalogJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MonitorPatientVitalsJPanel
     */
   
    private JPanel userProcessContainer;
    private UserAccount account;
    private LabOrganization organisation;
    private Enterprise etrp;
    private EcoSystem business;
   public ViewPatientCatalogJPanel(JPanel userProcessContainer, UserAccount account, LabOrganization organisation, Enterprise etrp, EcoSystem business) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.account=account;
       this.organisation=organisation;
       this.etrp=etrp;
       this.business=business;
       populatePersonDetails();
    }
   public void populatePersonDetails()
   {
       DefaultTableModel dtm=(DefaultTableModel) tblPatients.getModel();
      
       for(Person p:organisation.getPersonDirectory().getLstPerson())
       {
         Object[] row=new Object[4];
         row[0]=p;
         row[1]=p.getAge();
         row[2]=p.getGender().getValue();
         row[3]=p.getPreliminaryCheck();
         
         dtm.addRow(row);
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatients = new javax.swing.JTable();
        btnSelectPatient = new javax.swing.JButton();
        btnRemovePatient = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        tblPatients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Person Name", "Gender", "PreliminaryCheck?"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPatients);
        if (tblPatients.getColumnModel().getColumnCount() > 0) {
            tblPatients.getColumnModel().getColumn(0).setResizable(false);
            tblPatients.getColumnModel().getColumn(1).setResizable(false);
            tblPatients.getColumnModel().getColumn(2).setResizable(false);
        }

        btnSelectPatient.setText("Test Patient vitals");
        btnSelectPatient.setEnabled(false);
        btnSelectPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectPatientActionPerformed(evt);
            }
        });

        btnRemovePatient.setText("Remove Patient");
        btnRemovePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemovePatientActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("View Patient Catalog");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack)
                .addGap(28, 28, 28)
                .addComponent(btnRemovePatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                .addComponent(btnSelectPatient)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnSelectPatient)
                    .addComponent(btnRemovePatient))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemovePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemovePatientActionPerformed
        // TODO add your handling code here:
//        int selectedRow=tblPatients.getSelectedRow();
//        if(selectedRow>-1)
//        {
//            Person p=(Person) tblPatients.getValueAt(selectedRow,0);
//            int op=JOptionPane.showConfirmDialog(null,"Are you sure you want to remove this patient?");
//            if(op==0)
//            {
//            organisation.getPersonDirectory().removePerson(p);
//            JOptionPane.showMessageDialog(null,"Patient Removed successfully");
//            }
//            else
//                return;
//        }
//        else
//        {
//            JOptionPane.showMessageDialog(null, "Please select a patient from table","WARNING",JOptionPane.WARNING_MESSAGE);
//        }
    }//GEN-LAST:event_btnRemovePatientActionPerformed

    private void btnSelectPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectPatientActionPerformed
        // TODO add your handling code here:
         int selectedRow=tblPatients.getSelectedRow();
        if(selectedRow>-1)
        {
            Person p=(Person) tblPatients.getValueAt(selectedRow,0);
            if(p!=null)
            {
                organisation.getPersonDirectory().removePerson(p);
                JOptionPane.showMessageDialog(null,"Patient removed from catalog");
           // userProcessContainer.add("MonitorPatientVitalSignJPanel",new MonitorPatientVitalSignJPanel(userProcessContainer,p,account,organisation,etrp,business));
           // ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a patient from table","WARNING",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSelectPatientActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        ((CardLayout)userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRemovePatient;
    private javax.swing.JButton btnSelectPatient;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPatients;
    // End of variables declaration//GEN-END:variables
}
