/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CounsellorWorkAreaa;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.User.UserAccount;
import Business.WorkRequest.WorkRequest;
import Business.WorkRequest.WorkResponse;
import Interface.AdvisorWorkArea.TestingPatientJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suyog Sathe
 */
public class ManageCounsellorWorkRequestsJPanel extends javax.swing.JPanel {

   
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organisation;
    private Enterprise etrp;
    EcoSystem business;
    ManageCounsellorWorkRequestsJPanel(JPanel userProcessContainer, UserAccount account, Organization organisation, Enterprise etrp, EcoSystem business) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.account=account;
       this.organisation=organisation;
       this.etrp=etrp;
       this.business=business;
       populateWorkRequest();
       
    }

    public void populateWorkRequest()
    {
        DefaultTableModel dtm = (DefaultTableModel) counsellorTable.getModel();
        dtm.setRowCount(0);
        for(WorkRequest wr : organisation.getWorkQueue().getLstWorkRequest())
        {
            Object row[] = new Object[4];
            row[0]=wr;
            row[1]=wr.getPerson();
            row[2]=wr.getStatus();
            row[3]=wr.getReceiver()==null?"UnAssigned":wr.getReceiver();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        counsellorTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        assignBtn = new javax.swing.JButton();
        processBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Manage Work Requests");

        counsellorTable.setBackground(new java.awt.Color(0, 0, 0));
        counsellorTable.setBorder(new javax.swing.border.MatteBorder(null));
        counsellorTable.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 16)); // NOI18N
        counsellorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Work Request", "Person", "Status", "Receiver"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        counsellorTable.setGridColor(new java.awt.Color(0, 0, 0));
        counsellorTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(counsellorTable);
        if (counsellorTable.getColumnModel().getColumnCount() > 0) {
            counsellorTable.getColumnModel().getColumn(0).setResizable(false);
            counsellorTable.getColumnModel().getColumn(1).setResizable(false);
            counsellorTable.getColumnModel().getColumn(2).setResizable(false);
            counsellorTable.getColumnModel().getColumn(3).setResizable(false);
        }

        backBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        assignBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        assignBtn.setText("Assign");
        assignBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });

        processBtn.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        processBtn.setText("Process");
        processBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 999, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(759, 759, 759)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assignBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(processBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
         userProcessContainer.remove(this);
        ((CardLayout) userProcessContainer.getLayout()).previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        int selectedRow = counsellorTable.getSelectedRow();
        if (selectedRow > -1) {
            WorkRequest wr = (WorkRequest) counsellorTable.getValueAt(selectedRow, 0);
            if (!wr.getOl().equals(WorkRequest.OperationalLevel.CounsellingOrganization)) {
                JOptionPane.showMessageDialog(null, "Request is currently being served at" + wr.getOl().name() + " operational level", "WARNING", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (wr.getReceiver() != null && wr.getReceiver() != account) {
                JOptionPane.showMessageDialog(null, "Request is assigned to some other user", "WARNING", JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (wr.getReceiver() == account) {

                JOptionPane.showMessageDialog(null, "Request already assigned to current user", "WARNING", JOptionPane.WARNING_MESSAGE);
                return;
            }
            wr.setReceiver(account);
            JOptionPane.showMessageDialog(null, "Request id - " + wr.getRequestId() + " has been assigned to you!");
            populateWorkRequest();
        } else {
            JOptionPane.showMessageDialog(null, "Please select a request from table", "WARNING", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_assignBtnActionPerformed

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        int selectedRow=counsellorTable.getSelectedRow();
        if(selectedRow>-1)
        {
            WorkResponse wr=(WorkResponse) counsellorTable.getValueAt(selectedRow,0);
            if(wr!=null)
            {
                if(!wr.getOl().equals(WorkRequest.OperationalLevel.CounsellingOrganization))
                {
                    JOptionPane.showMessageDialog(null,"Request is being serviced at "+wr.getOl().name() +" operational level","WARNING",JOptionPane.WARNING_MESSAGE);
                    return;
                }
                if(wr.getReceiver()!=account)
                {
                    JOptionPane.showMessageDialog(null,"Request is not assigned to current user","WARNING",JOptionPane.WARNING_MESSAGE);
                    return;
                }
                userProcessContainer.add(new CounsellingQuestionnaireJPanel(userProcessContainer, wr,account, organisation, etrp, business));
                ((CardLayout)userProcessContainer.getLayout()).next(userProcessContainer);
            }
            }
        else
        {
            JOptionPane.showMessageDialog(null, "Please select a row","Warning",JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_processBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable counsellorTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton processBtn;
    // End of variables declaration//GEN-END:variables
}
